// AUTO-GENERATED FILE. DO NOT EDIT.
// Run `bun run generate:types` to refresh
import type { z } from "zod";

import type { AccountInsertSchema } from "@/lib/schemas/db-tables";
import type { AccountSchema } from "@/lib/schemas/db-tables";
import type { AccountUpdateSchema } from "@/lib/schemas/db-tables";
import type { AddChannelMembersInput } from "@/lib/schemas/channel";
import type { AddReactionInput } from "@/lib/schemas/message";
import type { ArchiveChannelInput } from "@/lib/schemas/channel";
import type { AttachmentInsertSchema } from "@/lib/schemas/db-tables";
import type { AttachmentOutput } from "@/lib/schemas/attachment";
import type { AttachmentSchema } from "@/lib/schemas/db-tables";
import type { AttachmentTypeSchema } from "@/lib/schemas/attachment";
import type { AttachmentUpdateSchema } from "@/lib/schemas/db-tables";
import type { AttachmentWithChannelOutput } from "@/lib/schemas/attachment";
import type { AttachmentWithMessageOutput } from "@/lib/schemas/attachment";
import type { AttachmentsListOutput } from "@/lib/schemas/attachment";
import type { AttachmentsWithChannelListOutput } from "@/lib/schemas/attachment";
import type { AttachmentsWithMessageListOutput } from "@/lib/schemas/attachment";
import type { AttendanceInsertSchema } from "@/lib/schemas/db-tables";
import type { AttendanceSchema } from "@/lib/schemas/db-tables";
import type { AttendanceUpdateSchema } from "@/lib/schemas/db-tables";
import type { ChannelInsertSchema } from "@/lib/schemas/db-tables";
import type { ChannelJoinRequestInput } from "@/lib/schemas/channel";
import type { ChannelJoinRequestInsertSchema } from "@/lib/schemas/db-tables";
import type { ChannelJoinRequestOutput } from "@/lib/schemas/channel";
import type { ChannelJoinRequestSchema } from "@/lib/schemas/db-tables";
import type { ChannelJoinRequestUpdateSchema } from "@/lib/schemas/db-tables";
import type { ChannelMemberInsertSchema } from "@/lib/schemas/db-tables";
import type { ChannelMemberOutput } from "@/lib/schemas/channel";
import type { ChannelMemberSchema } from "@/lib/schemas/db-tables";
import type { ChannelMemberUpdateSchema } from "@/lib/schemas/db-tables";
import type { ChannelMembersListOutput } from "@/lib/schemas/channel";
import type { ChannelOutput } from "@/lib/schemas/channel";
import type { ChannelSchema } from "@/lib/schemas/db-tables";
import type { ChannelTypeSchema } from "@/lib/schemas/db-tables";
import type { ChannelUpdateSchema } from "@/lib/schemas/db-tables";
import type { ChannelWithCreatorOutput } from "@/lib/schemas/channel";
import type { ChannelWithStatsOutput } from "@/lib/schemas/channel";
import type { ChannelsListOutput } from "@/lib/schemas/channel";
import type { CreateAnnouncementNotificationInput } from "@/lib/schemas/notification";
import type { CreateAttachmentInput } from "@/lib/schemas/attachment";
import type { CreateBulkAttachmentsInput } from "@/lib/schemas/attachment";
import type { CreateBulkNotificationsInput } from "@/lib/schemas/notification";
import type { CreateChannelInput } from "@/lib/schemas/channel";
import type { CreateChannelInviteNotificationInput } from "@/lib/schemas/notification";
import type { CreateChannelOutput } from "@/lib/schemas/channel";
import type { CreateMessageInput } from "@/lib/schemas/message";
import type { CreateNotificationInput } from "@/lib/schemas/notification";
import type { CreateSystemNotificationInput } from "@/lib/schemas/notification";
import type { DeleteAttachmentInput } from "@/lib/schemas/attachment";
import type { DeleteAttachmentOutput } from "@/lib/schemas/attachment";
import type { DeleteChannelInput } from "@/lib/schemas/channel";
import type { DeleteMessageInput } from "@/lib/schemas/message";
import type { DeleteNotificationInput } from "@/lib/schemas/notification";
import type { DismissNotificationInput } from "@/lib/schemas/notification";
import type { FeatureSchema } from "@/lib/schemas/module";
import type { GetAttachmentInput } from "@/lib/schemas/attachment";
import type { GetChannelAttachmentsInput } from "@/lib/schemas/attachment";
import type { GetChannelInput } from "@/lib/schemas/channel";
import type { GetChannelMembersInput } from "@/lib/schemas/channel";
import type { GetChannelMembersOutput } from "@/lib/schemas/channel";
import type { GetChannelMessagesInput } from "@/lib/schemas/message";
import type { GetChannelMessagesOutput } from "@/lib/schemas/message";
import type { GetChannelsInput } from "@/lib/schemas/channel";
import type { GetDirectMessagesInput } from "@/lib/schemas/message";
import type { GetMessageAttachmentsInput } from "@/lib/schemas/attachment";
import type { GetMessageInput } from "@/lib/schemas/message";
import type { GetMultipleMessageAttachmentsInput } from "@/lib/schemas/attachment";
import type { GetNotificationsInput } from "@/lib/schemas/notification";
import type { GetRecentAttachmentsInput } from "@/lib/schemas/attachment";
import type { GetStorageStatsInput } from "@/lib/schemas/attachment";
import type { GetThreadMessagesInput } from "@/lib/schemas/message";
import type { GetUnreadCountInput } from "@/lib/schemas/message";
import type { GetUserAttachmentsInput } from "@/lib/schemas/attachment";
import type { InvitationInsertSchema } from "@/lib/schemas/db-tables";
import type { InvitationSchema } from "@/lib/schemas/db-tables";
import type { InvitationUpdateSchema } from "@/lib/schemas/db-tables";
import type { IsChannelMemberInput } from "@/lib/schemas/channel";
import type { IsChannelMemberOutput } from "@/lib/schemas/channel";
import type { JoinChannelInput } from "@/lib/schemas/channel";
import type { LeaveChannelInput } from "@/lib/schemas/channel";
import type { ListChannelsInput } from "@/lib/schemas/channel";
import type { ListChannelsOutput } from "@/lib/schemas/channel";
import type { MarkMessageAsReadInput } from "@/lib/schemas/message";
import type { MarkMultipleAsReadInput } from "@/lib/schemas/notification";
import type { MarkNotificationAsReadInput } from "@/lib/schemas/notification";
import type { MemberAttendanceStatusOutput } from "@/lib/schemas/attendance";
import type { MemberInsertSchema } from "@/lib/schemas/db-tables";
import type { MemberPunchInInput } from "@/lib/schemas/attendance";
import type { MemberPunchInOutput } from "@/lib/schemas/attendance";
import type { MemberPunchOutInput } from "@/lib/schemas/attendance";
import type { MemberPunchOutOutput } from "@/lib/schemas/attendance";
import type { MemberSchema } from "@/lib/schemas/db-tables";
import type { MemberUpdateSchema } from "@/lib/schemas/db-tables";
import type { MessageAttachmentOutput } from "@/lib/schemas/message";
import type { MessageInsertSchema } from "@/lib/schemas/db-tables";
import type { MessageOutput } from "@/lib/schemas/message";
import type { MessageReadInsertSchema } from "@/lib/schemas/db-tables";
import type { MessageReadSchema } from "@/lib/schemas/db-tables";
import type { MessageReadUpdateSchema } from "@/lib/schemas/db-tables";
import type { MessageSchema } from "@/lib/schemas/db-tables";
import type { MessageTypeSchema } from "@/lib/schemas/message";
import type { MessageUpdateSchema } from "@/lib/schemas/db-tables";
import type { MessageWithSenderOutput } from "@/lib/schemas/message";
import type { MessagesListOutput } from "@/lib/schemas/message";
import type { ModuleSchema } from "@/lib/schemas/module";
import type { NotificationInsertSchema } from "@/lib/schemas/db-tables";
import type { NotificationOutput } from "@/lib/schemas/notification";
import type { NotificationSchema } from "@/lib/schemas/db-tables";
import type { NotificationStatusSchema } from "@/lib/schemas/notification";
import type { NotificationTypeSchema } from "@/lib/schemas/notification";
import type { NotificationUpdateSchema } from "@/lib/schemas/db-tables";
import type { NotificationsListOutput } from "@/lib/schemas/notification";
import type { OrganizationInsertSchema } from "@/lib/schemas/db-tables";
import type { OrganizationSchema } from "@/lib/schemas/db-tables";
import type { OrganizationUpdateSchema } from "@/lib/schemas/db-tables";
import type { PinMessageInput } from "@/lib/schemas/message";
import type { PinMessageOutput } from "@/lib/schemas/message";
import type { RecentAttachmentOutput } from "@/lib/schemas/attachment";
import type { RecentAttachmentsListOutput } from "@/lib/schemas/attachment";
import type { RemoveChannelMemberInput } from "@/lib/schemas/channel";
import type { RemoveReactionInput } from "@/lib/schemas/message";
import type { RoleSchema } from "@/lib/schemas/module";
import type { SearchAttachmentsInput } from "@/lib/schemas/attachment";
import type { SearchMessageOutput } from "@/lib/schemas/message";
import type { SearchMessagesInput } from "@/lib/schemas/message";
import type { SearchMessagesListOutput } from "@/lib/schemas/message";
import type { SearchUsersInput } from "@/lib/schemas/message";
import type { SearchUsersOutput } from "@/lib/schemas/message";
import type { SessionInsertSchema } from "@/lib/schemas/db-tables";
import type { SessionSchema } from "@/lib/schemas/db-tables";
import type { SessionUpdateSchema } from "@/lib/schemas/db-tables";
import type { StorageStatsOutput } from "@/lib/schemas/attachment";
import type { SuccessOutput } from "@/lib/schemas/channel";
import type { TeamInsertSchema } from "@/lib/schemas/db-tables";
import type { TeamMemberInsertSchema } from "@/lib/schemas/db-tables";
import type { TeamMemberSchema } from "@/lib/schemas/db-tables";
import type { TeamMemberUpdateSchema } from "@/lib/schemas/db-tables";
import type { TeamSchema } from "@/lib/schemas/db-tables";
import type { TeamUpdateSchema } from "@/lib/schemas/db-tables";
import type { ThreadMessageOutput } from "@/lib/schemas/message";
import type { ThreadMessagesListOutput } from "@/lib/schemas/message";
import type { UnPinMessageInput } from "@/lib/schemas/message";
import type { UnPinMessageOutput } from "@/lib/schemas/message";
import type { UnreadCountOutput } from "@/lib/schemas/message";
import type { UpdateAttachmentInput } from "@/lib/schemas/attachment";
import type { UpdateChannelInput } from "@/lib/schemas/channel";
import type { UpdateChannelMemberInput } from "@/lib/schemas/channel";
import type { UpdateMessageInput } from "@/lib/schemas/message";
import type { UserInsertSchema } from "@/lib/schemas/db-tables";
import type { UserSchema } from "@/lib/schemas/db-tables";
import type { UserUpdateSchema } from "@/lib/schemas/db-tables";
import type { VerificationInsertSchema } from "@/lib/schemas/db-tables";
import type { VerificationSchema } from "@/lib/schemas/db-tables";
import type { VerificationUpdateSchema } from "@/lib/schemas/db-tables";

export type AccountInsertType = z.infer<typeof AccountInsertSchema>;
export type AccountType = z.infer<typeof AccountSchema>;
export type AccountUpdateType = z.infer<typeof AccountUpdateSchema>;
export type AddChannelMembersInputType = z.infer<typeof AddChannelMembersInput>;
export type AddReactionInputType = z.infer<typeof AddReactionInput>;
export type ArchiveChannelInputType = z.infer<typeof ArchiveChannelInput>;
export type AttachmentInsertType = z.infer<typeof AttachmentInsertSchema>;
export type AttachmentOutputType = z.infer<typeof AttachmentOutput>;
export type AttachmentType = z.infer<typeof AttachmentSchema>;
export type AttachmentTypeType = z.infer<typeof AttachmentTypeSchema>;
export type AttachmentUpdateType = z.infer<typeof AttachmentUpdateSchema>;
export type AttachmentWithChannelOutputType = z.infer<typeof AttachmentWithChannelOutput>;
export type AttachmentWithMessageOutputType = z.infer<typeof AttachmentWithMessageOutput>;
export type AttachmentsListOutputType = z.infer<typeof AttachmentsListOutput>;
export type AttachmentsWithChannelListOutputType = z.infer<typeof AttachmentsWithChannelListOutput>;
export type AttachmentsWithMessageListOutputType = z.infer<typeof AttachmentsWithMessageListOutput>;
export type AttendanceInsertType = z.infer<typeof AttendanceInsertSchema>;
export type AttendanceType = z.infer<typeof AttendanceSchema>;
export type AttendanceUpdateType = z.infer<typeof AttendanceUpdateSchema>;
export type ChannelInsertType = z.infer<typeof ChannelInsertSchema>;
export type ChannelJoinRequestInputType = z.infer<typeof ChannelJoinRequestInput>;
export type ChannelJoinRequestInsertType = z.infer<typeof ChannelJoinRequestInsertSchema>;
export type ChannelJoinRequestOutputType = z.infer<typeof ChannelJoinRequestOutput>;
export type ChannelJoinRequestType = z.infer<typeof ChannelJoinRequestSchema>;
export type ChannelJoinRequestUpdateType = z.infer<typeof ChannelJoinRequestUpdateSchema>;
export type ChannelMemberInsertType = z.infer<typeof ChannelMemberInsertSchema>;
export type ChannelMemberOutputType = z.infer<typeof ChannelMemberOutput>;
export type ChannelMemberType = z.infer<typeof ChannelMemberSchema>;
export type ChannelMemberUpdateType = z.infer<typeof ChannelMemberUpdateSchema>;
export type ChannelMembersListOutputType = z.infer<typeof ChannelMembersListOutput>;
export type ChannelOutputType = z.infer<typeof ChannelOutput>;
export type ChannelType = z.infer<typeof ChannelSchema>;
export type ChannelTypeType = z.infer<typeof ChannelTypeSchema>;
export type ChannelUpdateType = z.infer<typeof ChannelUpdateSchema>;
export type ChannelWithCreatorOutputType = z.infer<typeof ChannelWithCreatorOutput>;
export type ChannelWithStatsOutputType = z.infer<typeof ChannelWithStatsOutput>;
export type ChannelsListOutputType = z.infer<typeof ChannelsListOutput>;
export type CreateAnnouncementNotificationInputType = z.infer<typeof CreateAnnouncementNotificationInput>;
export type CreateAttachmentInputType = z.infer<typeof CreateAttachmentInput>;
export type CreateBulkAttachmentsInputType = z.infer<typeof CreateBulkAttachmentsInput>;
export type CreateBulkNotificationsInputType = z.infer<typeof CreateBulkNotificationsInput>;
export type CreateChannelInputType = z.infer<typeof CreateChannelInput>;
export type CreateChannelInviteNotificationInputType = z.infer<typeof CreateChannelInviteNotificationInput>;
export type CreateChannelOutputType = z.infer<typeof CreateChannelOutput>;
export type CreateMessageInputType = z.infer<typeof CreateMessageInput>;
export type CreateNotificationInputType = z.infer<typeof CreateNotificationInput>;
export type CreateSystemNotificationInputType = z.infer<typeof CreateSystemNotificationInput>;
export type DeleteAttachmentInputType = z.infer<typeof DeleteAttachmentInput>;
export type DeleteAttachmentOutputType = z.infer<typeof DeleteAttachmentOutput>;
export type DeleteChannelInputType = z.infer<typeof DeleteChannelInput>;
export type DeleteMessageInputType = z.infer<typeof DeleteMessageInput>;
export type DeleteNotificationInputType = z.infer<typeof DeleteNotificationInput>;
export type DismissNotificationInputType = z.infer<typeof DismissNotificationInput>;
export type FeatureType = z.infer<typeof FeatureSchema>;
export type GetAttachmentInputType = z.infer<typeof GetAttachmentInput>;
export type GetChannelAttachmentsInputType = z.infer<typeof GetChannelAttachmentsInput>;
export type GetChannelInputType = z.infer<typeof GetChannelInput>;
export type GetChannelMembersInputType = z.infer<typeof GetChannelMembersInput>;
export type GetChannelMembersOutputType = z.infer<typeof GetChannelMembersOutput>;
export type GetChannelMessagesInputType = z.infer<typeof GetChannelMessagesInput>;
export type GetChannelMessagesOutputType = z.infer<typeof GetChannelMessagesOutput>;
export type GetChannelsInputType = z.infer<typeof GetChannelsInput>;
export type GetDirectMessagesInputType = z.infer<typeof GetDirectMessagesInput>;
export type GetMessageAttachmentsInputType = z.infer<typeof GetMessageAttachmentsInput>;
export type GetMessageInputType = z.infer<typeof GetMessageInput>;
export type GetMultipleMessageAttachmentsInputType = z.infer<typeof GetMultipleMessageAttachmentsInput>;
export type GetNotificationsInputType = z.infer<typeof GetNotificationsInput>;
export type GetRecentAttachmentsInputType = z.infer<typeof GetRecentAttachmentsInput>;
export type GetStorageStatsInputType = z.infer<typeof GetStorageStatsInput>;
export type GetThreadMessagesInputType = z.infer<typeof GetThreadMessagesInput>;
export type GetUnreadCountInputType = z.infer<typeof GetUnreadCountInput>;
export type GetUserAttachmentsInputType = z.infer<typeof GetUserAttachmentsInput>;
export type InvitationInsertType = z.infer<typeof InvitationInsertSchema>;
export type InvitationType = z.infer<typeof InvitationSchema>;
export type InvitationUpdateType = z.infer<typeof InvitationUpdateSchema>;
export type IsChannelMemberInputType = z.infer<typeof IsChannelMemberInput>;
export type IsChannelMemberOutputType = z.infer<typeof IsChannelMemberOutput>;
export type JoinChannelInputType = z.infer<typeof JoinChannelInput>;
export type LeaveChannelInputType = z.infer<typeof LeaveChannelInput>;
export type ListChannelsInputType = z.infer<typeof ListChannelsInput>;
export type ListChannelsOutputType = z.infer<typeof ListChannelsOutput>;
export type MarkMessageAsReadInputType = z.infer<typeof MarkMessageAsReadInput>;
export type MarkMultipleAsReadInputType = z.infer<typeof MarkMultipleAsReadInput>;
export type MarkNotificationAsReadInputType = z.infer<typeof MarkNotificationAsReadInput>;
export type MemberAttendanceStatusOutputType = z.infer<typeof MemberAttendanceStatusOutput>;
export type MemberInsertType = z.infer<typeof MemberInsertSchema>;
export type MemberPunchInInputType = z.infer<typeof MemberPunchInInput>;
export type MemberPunchInOutputType = z.infer<typeof MemberPunchInOutput>;
export type MemberPunchOutInputType = z.infer<typeof MemberPunchOutInput>;
export type MemberPunchOutOutputType = z.infer<typeof MemberPunchOutOutput>;
export type MemberType = z.infer<typeof MemberSchema>;
export type MemberUpdateType = z.infer<typeof MemberUpdateSchema>;
export type MessageAttachmentOutputType = z.infer<typeof MessageAttachmentOutput>;
export type MessageInsertType = z.infer<typeof MessageInsertSchema>;
export type MessageOutputType = z.infer<typeof MessageOutput>;
export type MessageReadInsertType = z.infer<typeof MessageReadInsertSchema>;
export type MessageReadType = z.infer<typeof MessageReadSchema>;
export type MessageReadUpdateType = z.infer<typeof MessageReadUpdateSchema>;
export type MessageType = z.infer<typeof MessageSchema>;
export type MessageTypeType = z.infer<typeof MessageTypeSchema>;
export type MessageUpdateType = z.infer<typeof MessageUpdateSchema>;
export type MessageWithSenderOutputType = z.infer<typeof MessageWithSenderOutput>;
export type MessagesListOutputType = z.infer<typeof MessagesListOutput>;
export type ModuleType = z.infer<typeof ModuleSchema>;
export type NotificationInsertType = z.infer<typeof NotificationInsertSchema>;
export type NotificationOutputType = z.infer<typeof NotificationOutput>;
export type NotificationStatusType = z.infer<typeof NotificationStatusSchema>;
export type NotificationType = z.infer<typeof NotificationSchema>;
export type NotificationTypeType = z.infer<typeof NotificationTypeSchema>;
export type NotificationUpdateType = z.infer<typeof NotificationUpdateSchema>;
export type NotificationsListOutputType = z.infer<typeof NotificationsListOutput>;
export type OrganizationInsertType = z.infer<typeof OrganizationInsertSchema>;
export type OrganizationType = z.infer<typeof OrganizationSchema>;
export type OrganizationUpdateType = z.infer<typeof OrganizationUpdateSchema>;
export type PinMessageInputType = z.infer<typeof PinMessageInput>;
export type PinMessageOutputType = z.infer<typeof PinMessageOutput>;
export type RecentAttachmentOutputType = z.infer<typeof RecentAttachmentOutput>;
export type RecentAttachmentsListOutputType = z.infer<typeof RecentAttachmentsListOutput>;
export type RemoveChannelMemberInputType = z.infer<typeof RemoveChannelMemberInput>;
export type RemoveReactionInputType = z.infer<typeof RemoveReactionInput>;
export type RoleType = z.infer<typeof RoleSchema>;
export type SearchAttachmentsInputType = z.infer<typeof SearchAttachmentsInput>;
export type SearchMessageOutputType = z.infer<typeof SearchMessageOutput>;
export type SearchMessagesInputType = z.infer<typeof SearchMessagesInput>;
export type SearchMessagesListOutputType = z.infer<typeof SearchMessagesListOutput>;
export type SearchUsersInputType = z.infer<typeof SearchUsersInput>;
export type SearchUsersOutputType = z.infer<typeof SearchUsersOutput>;
export type SessionInsertType = z.infer<typeof SessionInsertSchema>;
export type SessionType = z.infer<typeof SessionSchema>;
export type SessionUpdateType = z.infer<typeof SessionUpdateSchema>;
export type StorageStatsOutputType = z.infer<typeof StorageStatsOutput>;
export type SuccessOutputType = z.infer<typeof SuccessOutput>;
export type TeamInsertType = z.infer<typeof TeamInsertSchema>;
export type TeamMemberInsertType = z.infer<typeof TeamMemberInsertSchema>;
export type TeamMemberType = z.infer<typeof TeamMemberSchema>;
export type TeamMemberUpdateType = z.infer<typeof TeamMemberUpdateSchema>;
export type TeamType = z.infer<typeof TeamSchema>;
export type TeamUpdateType = z.infer<typeof TeamUpdateSchema>;
export type ThreadMessageOutputType = z.infer<typeof ThreadMessageOutput>;
export type ThreadMessagesListOutputType = z.infer<typeof ThreadMessagesListOutput>;
export type UnPinMessageInputType = z.infer<typeof UnPinMessageInput>;
export type UnPinMessageOutputType = z.infer<typeof UnPinMessageOutput>;
export type UnreadCountOutputType = z.infer<typeof UnreadCountOutput>;
export type UpdateAttachmentInputType = z.infer<typeof UpdateAttachmentInput>;
export type UpdateChannelInputType = z.infer<typeof UpdateChannelInput>;
export type UpdateChannelMemberInputType = z.infer<typeof UpdateChannelMemberInput>;
export type UpdateMessageInputType = z.infer<typeof UpdateMessageInput>;
export type UserInsertType = z.infer<typeof UserInsertSchema>;
export type UserType = z.infer<typeof UserSchema>;
export type UserUpdateType = z.infer<typeof UserUpdateSchema>;
export type VerificationInsertType = z.infer<typeof VerificationInsertSchema>;
export type VerificationType = z.infer<typeof VerificationSchema>;
export type VerificationUpdateType = z.infer<typeof VerificationUpdateSchema>;
